-- Generated by tools/import_talent_effects.py; do not edit.
-- Verified text at the captured level/build. Active ability numbers may scale with level or gear.
local _, ns = ...

ns.Data.WARRIOR.TalentEffects = {
  _status = "verified",
  source = "data/probe/2026-10-05-warrior-12-talent-effects.json",
  sourceSha256 = "1ab0235e5255eb34ae4849920ab0e1d4f31bb0d2fe52016251508cfda44d36d0",
  sourceBuild = "1.60.1.70205",
  capturedAt = "2026-10-05 18:14:01",
  observedAtLevel = 12,
  ["Anger Management"] = {
    nodeID = 105951,
    entryID = 130681,
    spellID = 12296,
    ranks = {
      "Passive\010Generates 1 Rage every 3 sec while in combat, and reduce" ..
      "s Rage loss while out of combat by 30%.",
    },
  },
  ["Anticipation"] = {
    nodeID = 105975,
    entryID = 130705,
    spellID = 12297,
    ranks = {
      "Passive\010Increases your Defense Skill by 4.",
      "Passive\010Increases your Defense Skill by 8.",
      "Passive\010Increases your Defense Skill by 12.",
      "Passive\010Increases your Defense Skill by 16.",
      "Passive\010Increases your Defense Skill by 20.",
    },
  },
  ["Bastion"] = {
    nodeID = 105962,
    entryID = 130692,
    spellID = 16538,
    ranks = {
      "Passive\010Increases all damage you deal by 2% while a shield is eq" ..
      "uipped.",
      "Passive\010Increases all damage you deal by 4% while a shield is eq" ..
      "uipped.",
      "Passive\010Increases all damage you deal by 6% while a shield is eq" ..
      "uipped.",
      "Passive\010Increases all damage you deal by 8% while a shield is eq" ..
      "uipped.",
      "Passive\010Increases all damage you deal by 10% while a shield is e" ..
      "quipped.",
    },
  },
  ["Blood Craze"] = {
    nodeID = 105934,
    entryID = 130664,
    spellID = 16487,
    ranks = {
      "Passive\010Regenerates 1% of your total Health over 6 sec after bei" ..
      "ng the victim of a critical strike or suffering more than 20% of" ..
      " your maximum Health from a single attack.",
      "Passive\010Regenerates 2% of your total Health over 6 sec after bei" ..
      "ng the victim of a critical strike or suffering more than 20% of" ..
      " your maximum Health from a single attack.",
      "Passive\010Regenerates 3% of your total Health over 6 sec after bei" ..
      "ng the victim of a critical strike or suffering more than 20% of" ..
      " your maximum Health from a single attack.",
    },
  },
  ["Bloodthirst"] = {
    nodeID = 105930,
    entryID = 130660,
    spellID = 23881,
    ranks = {
      "30 Rage\010Melee Range\010Instant\0106 sec cooldown\010Instantly attack the " ..
      "target causing damage equal to 45% of your Attack Power plus 30 " ..
      "and increasing your movement speed by 10% for 10 sec.",
    },
  },
  ["Bloodthrill"] = {
    nodeID = 110524,
    entryID = 137214,
    spellID = 1289682,
    ranks = {
      "Passive\010Your Main Hand melee attacks against enemies afflicted b" ..
      "y your Rend have a 4% chance to allow the use of your Overpower " ..
      "ability on the target. Lasts 6 sec.",
      "Passive\010Your Main Hand melee attacks against enemies afflicted b" ..
      "y your Rend have a 8% chance to allow the use of your Overpower " ..
      "ability on the target. Lasts 6 sec.",
      "Passive\010Your Main Hand melee attacks against enemies afflicted b" ..
      "y your Rend have a 12% chance to allow the use of your Overpower" ..
      " ability on the target. Lasts 6 sec.",
      "Passive\010Your Main Hand melee attacks against enemies afflicted b" ..
      "y your Rend have a 16% chance to allow the use of your Overpower" ..
      " ability on the target. Lasts 6 sec.",
      "Passive\010Your Main Hand melee attacks against enemies afflicted b" ..
      "y your Rend have a 20% chance to allow the use of your Overpower" ..
      " ability on the target. Lasts 6 sec.",
    },
  },
  ["Booming Voice"] = {
    nodeID = 105938,
    entryID = 130668,
    spellID = 12321,
    ranks = {
      "Passive\010Increases the area of effect of your Shouts by 10% and r" ..
      "educes their Rage cost by 5%.",
      "Passive\010Increases the area of effect of your Shouts by 20% and r" ..
      "educes their Rage cost by 10%.",
      "Passive\010Increases the area of effect of your Shouts by 30% and r" ..
      "educes their Rage cost by 15%.",
      "Passive\010Increases the area of effect of your Shouts by 40% and r" ..
      "educes their Rage cost by 20%.",
      "Passive\010Increases the area of effect of your Shouts by 50% and r" ..
      "educes their Rage cost by 25%.",
    },
  },
  ["Concussion Blow"] = {
    nodeID = 105965,
    entryID = 130695,
    spellID = 12809,
    ranks = {
      "10 Rage\010Melee Range\010Instant\01045 sec cooldown\010Stuns the target for" ..
      " 5 sec.",
    },
  },
  ["Cruelty"] = {
    nodeID = 105939,
    entryID = 130669,
    spellID = 12320,
    ranks = {
      "Passive\010Improves your chance to get a critical strike with melee" ..
      " attacks by 1%.",
      "Passive\010Improves your chance to get a critical strike with melee" ..
      " attacks by 2%.",
      "Passive\010Improves your chance to get a critical strike with melee" ..
      " attacks by 3%.",
      "Passive\010Improves your chance to get a critical strike with melee" ..
      " attacks by 4%.",
      "Passive\010Improves your chance to get a critical strike with melee" ..
      " attacks by 5%.",
    },
  },
  ["Death Wish"] = {
    nodeID = 105927,
    entryID = 130657,
    spellID = 12328,
    ranks = {
      "10 Rage\010Instant\0103 min cooldown\010When activated, increases your Ph" ..
      "ysical damage done by 20% and makes you immune to Fear effects, " ..
      "but increases all damage you take by 5%. Lasts 30 sec.",
    },
  },
  ["Deep Wounds"] = {
    nodeID = 105950,
    entryID = 130680,
    spellID = 12834,
    ranks = {
      "Passive\010Your critical strikes cause your opponent to Bleed, deal" ..
      "ing 20% of your melee weapon's average damage over 12 sec.",
      "Passive\010Your critical strikes cause your opponent to Bleed, deal" ..
      "ing 40% of your melee weapon's average damage over 12 sec.",
      "Passive\010Your critical strikes cause your opponent to Bleed, deal" ..
      "ing 60% of your melee weapon's average damage over 12 sec.",
    },
  },
  ["Defiance"] = {
    nodeID = 110856,
    entryID = 137848,
    spellID = 12792,
    ranks = {
      "Passive\010Increases all threat generated in Defensive stance by an" ..
      " additional 5% while a shield is equipped.",
      "Passive\010Increases all threat generated in Defensive stance by an" ..
      " additional 10% while a shield is equipped.",
      "Passive\010Increases all threat generated in Defensive stance by an" ..
      " additional 15% while a shield is equipped.",
    },
  },
  ["Deflection"] = {
    nodeID = 105957,
    entryID = 130687,
    spellID = 16462,
    ranks = {
      "Passive\010Increases your Parry chance by 1%.",
      "Passive\010Increases your Parry chance by 2%.",
      "Passive\010Increases your Parry chance by 3%.",
      "Passive\010Increases your Parry chance by 4%.",
      "Passive\010Increases your Parry chance by 5%.",
    },
  },
  ["Dual Wield Specialization"] = {
    nodeID = 105933,
    entryID = 130663,
    spellID = 23584,
    ranks = {
      "Passive\010Increases the damage done by your off-hand weapon by 5% " ..
      "and the Rage generated by your off-hand attacks by 10%.",
      "Passive\010Increases the damage done by your off-hand weapon by 10%" ..
      " and the Rage generated by your off-hand attacks by 20%.",
      "Passive\010Increases the damage done by your off-hand weapon by 15%" ..
      " and the Rage generated by your off-hand attacks by 30%.",
      "Passive\010Increases the damage done by your off-hand weapon by 20%" ..
      " and the Rage generated by your off-hand attacks by 40%.",
      "Passive\010Increases the damage done by your off-hand weapon by 25%" ..
      " and the Rage generated by your off-hand attacks by 50%.",
    },
  },
  ["Enrage"] = {
    nodeID = 105931,
    entryID = 130661,
    spellID = 12317,
    ranks = {
      "Passive\010Gives you a 30% chance to deal 2% increased Physical dam" ..
      "age for 12 sec after being the victim of any damaging attack.",
      "Passive\010Gives you a 30% chance to deal 4% increased Physical dam" ..
      "age for 12 sec after being the victim of any damaging attack.",
      "Passive\010Gives you a 30% chance to deal 6% increased Physical dam" ..
      "age for 12 sec after being the victim of any damaging attack.",
      "Passive\010Gives you a 30% chance to deal 8% increased Physical dam" ..
      "age for 12 sec after being the victim of any damaging attack.",
      "Passive\010Gives you a 30% chance to deal 10% increased Physical da" ..
      "mage for 12 sec after being the victim of any damaging attack.",
    },
  },
  ["Flurry"] = {
    nodeID = 105928,
    entryID = 130658,
    spellID = 12319,
    ranks = {
      "Passive\010Increases your melee attack speed by 5% for your next 3 " ..
      "swings after dealing a melee critical strike.",
      "Passive\010Increases your melee attack speed by 10% for your next 3" ..
      " swings after dealing a melee critical strike.",
      "Passive\010Increases your melee attack speed by 15% for your next 3" ..
      " swings after dealing a melee critical strike.",
      "Passive\010Increases your melee attack speed by 20% for your next 3" ..
      " swings after dealing a melee critical strike.",
      "Passive\010Increases your melee attack speed by 25% for your next 3" ..
      " swings after dealing a melee critical strike.",
    },
  },
  ["Focused Rage"] = {
    nodeID = 105961,
    entryID = 130691,
    spellID = 29787,
    ranks = {
      "Passive\010Reduces the Rage cost of your offensive abilities by 1.",
      "Passive\010Reduces the Rage cost of your offensive abilities by 2.",
      "Passive\010Reduces the Rage cost of your offensive abilities by 3.",
    },
  },
  ["Furious Precision"] = {
    nodeID = 105953,
    entryID = 130683,
    spellID = 1323963,
    ranks = {
      "Passive\010Increases your chance to hit with off-hand attacks by 4%" ..
      ".",
      "Passive\010Increases your chance to hit with off-hand attacks by 7%" ..
      ".",
      "Passive\010Increases your chance to hit with off-hand attacks by 10" ..
      "%.",
    },
  },
  ["Gore Drinker"] = {
    nodeID = 113569,
    entryID = 141191,
    spellID = 1323967,
    ranks = {
      "Passive\010Your Enrage, Berserker Rage, Bloodrage, Death Wish, and " ..
      "Bloodthirst abilities cause your next 3 melee attacks to restore" ..
      " 0.5% of your maximum Health.",
      "Passive\010Your Enrage, Berserker Rage, Bloodrage, Death Wish, and " ..
      "Bloodthirst abilities cause your next 3 melee attacks to restore" ..
      " 1.0% of your maximum Health.",
    },
  },
  ["Impale"] = {
    nodeID = 105947,
    entryID = 130677,
    spellID = 16493,
    ranks = {
      "Passive\010Increases the critical strike damage bonus of your abili" ..
      "ties by 10%.",
      "Passive\010Increases the critical strike damage bonus of your abili" ..
      "ties by 20%.",
    },
  },
  ["Improved Berserker Rage"] = {
    nodeID = 105978,
    entryID = 130708,
    spellID = 20500,
    ranks = {
      "Passive\010Your Berserker Rage ability will instantly generate 5 Ra" ..
      "ge and has a 50% chance to remove all movement impairing effects" ..
      " when activated.",
      "Passive\010Your Berserker Rage ability will instantly generate 10 R" ..
      "age and has a 100% chance to remove all movement impairing effec" ..
      "ts when activated.",
    },
  },
  ["Improved Bloodrage"] = {
    nodeID = 105974,
    entryID = 130704,
    spellID = 12301,
    ranks = {
      "Passive\010Increases all the Rage generated by your Bloodrage abili" ..
      "ty by 25%.",
      "Passive\010Increases all the Rage generated by your Bloodrage abili" ..
      "ty by 50%.",
    },
  },
  ["Improved Charge"] = {
    nodeID = 105955,
    entryID = 130685,
    spellID = 12285,
    ranks = {
      "Passive\010Increases the Rage generated by your Charge ability by 3" ..
      ".",
      "Passive\010Increases the Rage generated by your Charge ability by 6" ..
      ".",
    },
  },
  ["Improved Disarm"] = {
    nodeID = 105967,
    entryID = 130697,
    spellID = 12313,
    ranks = {
      "Passive\010Reduces the cooldown of your Disarm ability by 7 secs.",
      "Passive\010Reduces the cooldown of your Disarm ability by 13 secs.",
      "Passive\010Reduces the cooldown of your Disarm ability by 20 secs.",
    },
  },
  ["Improved Execute"] = {
    nodeID = 105932,
    entryID = 130662,
    spellID = 20502,
    ranks = {
      "Passive\010Reduces the Rage cost of your Execute ability by 3.",
      "Passive\010Reduces the Rage cost of your Execute ability by 5.",
    },
  },
  ["Improved Hamstring"] = {
    nodeID = 105942,
    entryID = 130672,
    spellID = 12289,
    ranks = {
      "Passive\010Gives your Hamstring ability a 5% chance to immobilize t" ..
      "he target for 5 sec.",
      "Passive\010Gives your Hamstring ability a 10% chance to immobilize " ..
      "the target for 5 sec.",
      "Passive\010Gives your Hamstring ability a 15% chance to immobilize " ..
      "the target for 5 sec.",
    },
  },
  ["Improved Heroic Strike"] = {
    nodeID = 105958,
    entryID = 130688,
    spellID = 12282,
    ranks = {
      "Passive\010Reduces the cost of your Heroic Strike ability by 1 Rage" ..
      ".",
      "Passive\010Reduces the cost of your Heroic Strike ability by 2 Rage" ..
      ".",
      "Passive\010Reduces the cost of your Heroic Strike ability by 3 Rage" ..
      ".",
    },
  },
  ["Improved Intercept"] = {
    nodeID = 105926,
    entryID = 130656,
    spellID = 20504,
    ranks = {
      "Passive\010Reduces the cooldown of your Intercept ability by 5 sec.",
      "Passive\010Reduces the cooldown of your Intercept ability by 10 sec" ..
      ".",
    },
  },
  ["Improved Overpower"] = {
    nodeID = 105952,
    entryID = 130682,
    spellID = 12290,
    ranks = {
      "Passive\010Increases the critical strike chance of your Overpower a" ..
      "bility by 25%.",
      "Passive\010Increases the critical strike chance of your Overpower a" ..
      "bility by 50%.",
    },
  },
  ["Improved Rend"] = {
    nodeID = 105956,
    entryID = 130686,
    spellID = 12286,
    ranks = {
      "Passive\010Increases the Bleed damage done by your Rend ability by " ..
      "12%.",
      "Passive\010Increases the Bleed damage done by your Rend ability by " ..
      "23%.",
      "Passive\010Increases the Bleed damage done by your Rend ability by " ..
      "35%.",
    },
  },
  ["Improved Revenge"] = {
    nodeID = 105969,
    entryID = 130699,
    spellID = 12797,
    ranks = {
      "Passive\010Increases damage dealt by your Revenge ability by 20%.",
      "Passive\010Increases damage dealt by your Revenge ability by 40%.",
      "Passive\010Increases damage dealt by your Revenge ability by 60%.",
    },
  },
  ["Improved Shield Bash"] = {
    nodeID = 105963,
    entryID = 130693,
    spellID = 12311,
    ranks = {
      "Passive\010Gives your Shield Bash ability a 50% chance to Silence t" ..
      "he target for 3 sec.",
      "Passive\010Gives your Shield Bash ability a 100% chance to Silence " ..
      "the target for 3 sec.",
    },
  },
  ["Improved Shield Wall"] = {
    nodeID = 105964,
    entryID = 130694,
    spellID = 12312,
    ranks = {
      "Passive\010Reduces the cooldown of your Shield Wall ability by 5.5 " ..
      "min.",
      "Passive\010Reduces the cooldown of your Shield Wall ability by 11.0" ..
      " min.",
    },
  },
  ["Improved Slam"] = {
    nodeID = 110858,
    entryID = 137850,
    spellID = 12862,
    ranks = {
      "Passive\010Reduces the global cooldown and cast time of your Slam a" ..
      "bility by 0.25 sec. In addition, Slam no longer interrupts or de" ..
      "lays your melee swing and Slam's cooldown is reduced by 3.0 sec.",
      "Passive\010Reduces the global cooldown and cast time of your Slam a" ..
      "bility by 0.50 sec. In addition, Slam no longer interrupts or de" ..
      "lays your melee swing and Slam's cooldown is reduced by 3.0 sec.",
    },
  },
  ["Improved Sunder Armor"] = {
    nodeID = 105968,
    entryID = 130698,
    spellID = 12308,
    ranks = {
      "Passive\010Reduces the Rage cost of your Sunder Armor ability by 1.",
      "Passive\010Reduces the Rage cost of your Sunder Armor ability by 2.",
      "Passive\010Reduces the Rage cost of your Sunder Armor ability by 3.",
    },
  },
  ["Improved Tactical Mastery"] = {
    nodeID = 105954,
    entryID = 130684,
    spellID = 12295,
    ranks = {
      "Passive\010Tactical Mastery lets you retain up to an additional 3 R" ..
      "age when you change stances.",
      "Passive\010Tactical Mastery lets you retain up to an additional 6 R" ..
      "age when you change stances.",
      "Passive\010Tactical Mastery lets you retain up to an additional 9 R" ..
      "age when you change stances.",
      "Passive\010Tactical Mastery lets you retain up to an additional 12 " ..
      "Rage when you change stances.",
      "Passive\010Tactical Mastery lets you retain up to an additional 15 " ..
      "Rage when you change stances.",
    },
  },
  ["Improved Thunder Clap"] = {
    nodeID = 105972,
    entryID = 130702,
    spellID = 12287,
    ranks = {
      "Passive\010Reduces the Rage cost of your Thunder Clap ability by 2.",
      "Passive\010Reduces the Rage cost of your Thunder Clap ability by 4.",
      "Passive\010Reduces the Rage cost of your Thunder Clap ability by 6.",
    },
  },
  ["Iron Will"] = {
    nodeID = 113570,
    entryID = 141192,
    spellID = 12962,
    ranks = {
      "Passive\010Reduces the duration of Stun and Fear effects inflicted " ..
      "on you by 3%.",
      "Passive\010Reduces the duration of Stun and Fear effects inflicted " ..
      "on you by 6%.",
      "Passive\010Reduces the duration of Stun and Fear effects inflicted " ..
      "on you by 9%.",
      "Passive\010Reduces the duration of Stun and Fear effects inflicted " ..
      "on you by 12%.",
      "Passive\010Reduces the duration of Stun and Fear effects inflicted " ..
      "on you by 15%.",
    },
  },
  ["Last Stand"] = {
    nodeID = 105970,
    entryID = 130700,
    spellID = 12975,
    ranks = {
      "Instant\0103 min cooldown\010When activated, this ability temporarily " ..
      "grants you 30% of your maximum health for 20 sec. After the effe" ..
      "ct expires, the health is lost.",
    },
  },
  ["Lingering Rage"] = {
    nodeID = 110857,
    entryID = 137849,
    spellID = 1323964,
    ranks = {
      "Passive\010Increases the time before your Rage begins to decay afte" ..
      "r leaving combat by 2 sec.",
      "Passive\010Increases the time before your Rage begins to decay afte" ..
      "r leaving combat by 4 sec.",
      "Passive\010Increases the time before your Rage begins to decay afte" ..
      "r leaving combat by 6 sec.",
      "Passive\010Increases the time before your Rage begins to decay afte" ..
      "r leaving combat by 8 sec.",
      "Passive\010Increases the time before your Rage begins to decay afte" ..
      "r leaving combat by 10 sec.",
    },
  },
  ["Master of Defense"] = {
    nodeID = 105971,
    entryID = 130701,
    spellID = 1310316,
    ranks = {
      "Passive\010Grants you a 50% chance to generate 5 Rage when you Dodg" ..
      "e or Parry while a shield is equipped.",
      "Passive\010Grants you a 100% chance to generate 5 Rage when you Dod" ..
      "ge or Parry while a shield is equipped.",
    },
  },
  ["Mortal Strike"] = {
    nodeID = 105941,
    entryID = 130671,
    spellID = 12294,
    ranks = {
      "30 Rage\010Melee Range\010Instant\0106 sec cooldown\010A vicious strike that" ..
      " deals weapon damage plus 85 and wounds the target, reducing the" ..
      " effectiveness of any healing by 50% for 10 sec.",
    },
  },
  ["Piercing Howl"] = {
    nodeID = 105935,
    entryID = 130665,
    spellID = 12323,
    ranks = {
      "10 Rage\010Instant\010Causes all enemies within 10 yds to be Dazed, re" ..
      "ducing movement speed by 50% for 6 sec.",
    },
  },
  ["Raging Blows"] = {
    nodeID = 105977,
    entryID = 130707,
    spellID = 1310315,
    ranks = {
      "Passive\010Reduces the Rage cost of your Cleave and Whirlwind abili" ..
      "ties by 3.",
    },
  },
  ["Shield Slam"] = {
    nodeID = 105959,
    entryID = 130689,
    spellID = 23922,
    ranks = {
      "20 Rage\010Melee Range\010Instant\0106 sec cooldown\010Slam the target with " ..
      "your shield, causing 421 to 439 damage, increased by your Block " ..
      "Value, and has a 50% chance of dispelling 1 magic effect on the " ..
      "target. Causes a very high amount of threat.",
    },
  },
  ["Shield Specialization"] = {
    nodeID = 105976,
    entryID = 130706,
    spellID = 12298,
    ranks = {
      "Passive\010Increases your chance to Block attacks with your shield " ..
      "by 1% and grants you a 20% chance to generate 5 Rage when you Bl" ..
      "ock.",
      "Passive\010Increases your chance to Block attacks with your shield " ..
      "by 2% and grants you a 40% chance to generate 5 Rage when you Bl" ..
      "ock.",
      "Passive\010Increases your chance to Block attacks with your shield " ..
      "by 3% and grants you a 60% chance to generate 5 Rage when you Bl" ..
      "ock.",
      "Passive\010Increases your chance to Block attacks with your shield " ..
      "by 4% and grants you a 80% chance to generate 5 Rage when you Bl" ..
      "ock.",
      "Passive\010Increases your chance to Block attacks with your shield " ..
      "by 5% and grants you a 100% chance to generate 5 Rage when you B" ..
      "lock.",
    },
  },
  ["Spearing Strike"] = {
    nodeID = 105949,
    entryID = 130679,
    spellID = 1310222,
    ranks = {
      "15 Rage\010Melee Range\010Instant\01020 sec cooldown\010Requires Battle Stan" ..
      "ce\010A brutal attack that deals 40% weapon damage, plus an additio" ..
      "nal 80% weapon damage against Giants, Dragonkin, and mounted tar" ..
      "gets.",
    },
  },
  ["Sweeping Strikes"] = {
    nodeID = 105945,
    entryID = 130675,
    spellID = 12292,
    ranks = {
      "30 Rage\010Instant\01030 sec cooldown\010Requires Battle Stance\010Your next" ..
      " 5 melee attacks strike an additional nearby opponent.",
    },
  },
  ["Two-Handed Weapon Specialization"] = {
    nodeID = 105948,
    entryID = 130678,
    spellID = 12163,
    ranks = {
      "Passive\010Increases the damage you deal with two-handed melee weap" ..
      "ons by 1%.",
      "Passive\010Increases the damage you deal with two-handed melee weap" ..
      "ons by 2%.",
      "Passive\010Increases the damage you deal with two-handed melee weap" ..
      "ons by 3%.",
    },
  },
  ["Unbridled Wrath"] = {
    nodeID = 105937,
    entryID = 130667,
    spellID = 12322,
    ranks = {
      "Passive\010Gives you a 12% chance to generate 1 additional Rage whe" ..
      "n you deal melee damage with a weapon.",
      "Passive\010Gives you a 24% chance to generate 1 additional Rage whe" ..
      "n you deal melee damage with a weapon.",
      "Passive\010Gives you a 36% chance to generate 1 additional Rage whe" ..
      "n you deal melee damage with a weapon.",
      "Passive\010Gives you a 48% chance to generate 1 additional Rage whe" ..
      "n you deal melee damage with a weapon.",
      "Passive\010Gives you a 60% chance to generate 1 additional Rage whe" ..
      "n you deal melee damage with a weapon.",
    },
  },
  ["Vanguard"] = {
    nodeID = 105966,
    entryID = 130696,
    spellID = 1310317,
    ranks = {
      "Passive\010Your Charge ability is now usable while in Defensive Sta" ..
      "nce.",
    },
  },
  ["Weaponmaster"] = {
    nodeID = 105944,
    entryID = 130674,
    spellID = 1290261,
    ranks = {
      "Passive\010Gives your melee weapon attacks a benefit depending on t" ..
      "he weapon.\013\010\013\010    |CFFFFFFFFAxe/Polearm:|R Increases your\013\010    c" ..
      "ritical strike chance by 1%.\013\010\013\010    |CFFFFFFFFMace/Staff:|R Your" ..
      " attacks ignore\013\010    3% of your target's armor.\013\010\013\010    |CFFFFFFF" ..
      "FSword:|R Your successful melee \013\010    attacks have a 1% chance t" ..
      "o \013\010    trigger an extra attack on the \013\010    target.",
      "Passive\010Gives your melee weapon attacks a benefit depending on t" ..
      "he weapon.\013\010\013\010    |CFFFFFFFFAxe/Polearm:|R Increases your\013\010    c" ..
      "ritical strike chance by 2%.\013\010\013\010    |CFFFFFFFFMace/Staff:|R Your" ..
      " attacks ignore\013\010    6% of your target's armor.\013\010\013\010    |CFFFFFFF" ..
      "FSword:|R Your successful melee \013\010    attacks have a 2% chance t" ..
      "o \013\010    trigger an extra attack on the \013\010    target.",
      "Passive\010Gives your melee weapon attacks a benefit depending on t" ..
      "he weapon.\013\010\013\010    |CFFFFFFFFAxe/Polearm:|R Increases your\013\010    c" ..
      "ritical strike chance by 3%.\013\010\013\010    |CFFFFFFFFMace/Staff:|R Your" ..
      " attacks ignore\013\010    9% of your target's armor.\013\010\013\010    |CFFFFFFF" ..
      "FSword:|R Your successful melee \013\010    attacks have a 3% chance t" ..
      "o \013\010    trigger an extra attack on the \013\010    target.",
      "Passive\010Gives your melee weapon attacks a benefit depending on t" ..
      "he weapon.\013\010\013\010    |CFFFFFFFFAxe/Polearm:|R Increases your\013\010    c" ..
      "ritical strike chance by 4%.\013\010\013\010    |CFFFFFFFFMace/Staff:|R Your" ..
      " attacks ignore\013\010    12% of your target's armor.\013\010\013\010    |CFFFFFF" ..
      "FFSword:|R Your successful melee \013\010    attacks have a 4% chance " ..
      "to \013\010    trigger an extra attack on the \013\010    target.",
      "Passive\010Gives your melee weapon attacks a benefit depending on t" ..
      "he weapon.\013\010\013\010    |CFFFFFFFFAxe/Polearm:|R Increases your\013\010    c" ..
      "ritical strike chance by 5%.\013\010\013\010    |CFFFFFFFFMace/Staff:|R Your" ..
      " attacks ignore\013\010    15% of your target's armor.\013\010\013\010    |CFFFFFF" ..
      "FFSword:|R Your successful melee \013\010    attacks have a 5% chance " ..
      "to \013\010    trigger an extra attack on the \013\010    target.",
    },
  },
}
