-- Generated by tools/import_gear_catalog.py; do not edit.
-- Client-derived item/recipe facts; access and usability are unconfirmed.
local _, ns = ...

local items = {
  {
    _status = "provisional",
    itemID = 2300, name = "Embossed Leather Vest",
    slot = 5, minLevel = 7, icon = 132724,
    classes = { ROGUE = true },
    stats = { ARMOR = 62, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2300:2160", recipeID = 2160,
        name = "Embossed Leather Vest", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2303, name = "Handstitched Leather Pants",
    slot = 7, minLevel = 5, icon = 134706,
    classes = { ROGUE = true },
    stats = { AGILITY = 1, ARMOR = 48 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2303:2153", recipeID = 2153,
        name = "Handstitched Leather Pants", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2307, name = "Fine Leather Boots",
    slot = 8, minLevel = 13, icon = 132540,
    classes = { ROGUE = true },
    stats = { AGILITY = 3, ARMOR = 51, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2307:2158", recipeID = 2158,
        name = "Fine Leather Boots", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2308, name = "Fine Leather Cloak",
    slot = 15, minLevel = 10, icon = 133762,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { ARMOR = 14, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2308:2159", recipeID = 2159,
        name = "Fine Leather Cloak", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2309, name = "Embossed Leather Boots",
    slot = 8, minLevel = 10, icon = 132539,
    classes = { ROGUE = true },
    stats = { ARMOR = 48, SPELL_POWER = 2, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2309:2161", recipeID = 2161,
        name = "Embossed Leather Boots", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2310, name = "Embossed Leather Cloak",
    slot = 15, minLevel = 8, icon = 133150,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { AGILITY = 1, ARMOR = 12 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2310:2162", recipeID = 2162,
        name = "Embossed Leather Cloak", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2311, name = "White Leather Jerkin",
    slot = 5, minLevel = 8, icon = 132760,
    classes = { ROGUE = true },
    stats = { ARMOR = 65, SPELL_POWER = 2, STRENGTH = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2311:2163", recipeID = 2163,
        name = "White Leather Jerkin", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2312, name = "Fine Leather Gloves",
    slot = 10, minLevel = 10, icon = 132939,
    classes = { ROGUE = true },
    stats = { ARMOR = 43, INTELLECT = 2, SPELL_POWER = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2312:2164", recipeID = 2164,
        name = "Fine Leather Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2315, name = "Dark Leather Boots",
    slot = 8, minLevel = 15, icon = 132539,
    classes = { ROGUE = true },
    stats = { AGILITY = 5, ARMOR = 53 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2315:2167", recipeID = 2167,
        name = "Dark Leather Boots", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2316, name = "Dark Leather Cloak",
    slot = 15, minLevel = 17, icon = 133762,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { AGILITY = 3, ARMOR = 18, STRENGTH = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2316:2168", recipeID = 2168,
        name = "Dark Leather Cloak", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2317, name = "Dark Leather Tunic",
    slot = 5, minLevel = 15, icon = 132718,
    classes = { ROGUE = true },
    stats = { AGILITY = 6, ARMOR = 78 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2317:2169", recipeID = 2169,
        name = "Dark Leather Tunic", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2569, name = "Linen Boots",
    slot = 8, minLevel = 8, icon = 132543,
    classes = { PRIEST = true },
    stats = { ARMOR = 17, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2569:2386", recipeID = 2386,
        name = "Linen Boots", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2572, name = "Red Linen Robe",
    slot = 5, minLevel = 5, icon = 132659,
    classes = { PRIEST = true },
    stats = { ARMOR = 19, INTELLECT = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2572:2389", recipeID = 2389,
        name = "Red Linen Robe", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2578, name = "Barbaric Linen Vest",
    slot = 5, minLevel = 9, icon = 132715,
    classes = { PRIEST = true },
    stats = { ARMOR = 26, SPELL_POWER = 2, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2578:2395", recipeID = 2395,
        name = "Barbaric Linen Vest", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2580, name = "Reinforced Linen Cape",
    slot = 15, minLevel = 7, icon = 133759,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { ARMOR = 11, SPELL_POWER = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2580:2397", recipeID = 2397,
        name = "Reinforced Linen Cape", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2582, name = "Green Woolen Vest",
    slot = 5, minLevel = 12, icon = 132680,
    classes = { PRIEST = true },
    stats = { ARMOR = 30, SPELL_POWER = 4, SPIRIT = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2582:2399", recipeID = 2399,
        name = "Green Woolen Vest", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2583, name = "Woolen Boots",
    slot = 8, minLevel = 14, icon = 132543,
    classes = { PRIEST = true },
    stats = { ARMOR = 22, INTELLECT = 2, SPELL_POWER = 2, SPIRIT = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2583:2401", recipeID = 2401,
        name = "Woolen Boots", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2584, name = "Woolen Cape",
    slot = 15, minLevel = 11, icon = 133762,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { ARMOR = 15, SPELL_POWER = 1, SPIRIT = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2584:2402", recipeID = 2402,
        name = "Woolen Cape", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2585, name = "Gray Woolen Robe",
    slot = 5, minLevel = 16, icon = 132654,
    classes = { PRIEST = true },
    stats = { ARMOR = 35, INTELLECT = 5, SPELL_POWER = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2585:2403", recipeID = 2403,
        name = "Gray Woolen Robe", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2851, name = "Copper Chain Belt",
    slot = 6, minLevel = 6, icon = 132491,
    classes = { WARRIOR = true },
    stats = { ARMOR = 65, STAMINA = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2851:2661", recipeID = 2661,
        name = "Copper Chain Belt", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2852, name = "Copper Chain Pants",
    slot = 7, minLevel = 4, icon = 134583,
    classes = { WARRIOR = true },
    stats = { ARMOR = 94, STAMINA = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2852:2662", recipeID = 2662,
        name = "Copper Chain Pants", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2854, name = "Runed Copper Bracers",
    slot = 9, minLevel = 14, icon = 132602,
    classes = { WARRIOR = true },
    stats = { ARMOR = 72, STAMINA = 2, STRENGTH = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2854:2664", recipeID = 2664,
        name = "Runed Copper Bracers", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2857, name = "Runed Copper Belt",
    slot = 6, minLevel = 13, icon = 132492,
    classes = { WARRIOR = true },
    stats = { ARMOR = 91, STAMINA = 2, STRENGTH = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2857:2666", recipeID = 2666,
        name = "Runed Copper Belt", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2864, name = "Runed Copper Breastplate",
    slot = 5, minLevel = 13, icon = 132738,
    classes = { WARRIOR = true },
    stats = { ARMOR = 162, STAMINA = 3, STRENGTH = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2864:2667", recipeID = 2667,
        name = "Runed Copper Breastplate", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2865, name = "Rough Bronze Leggings",
    slot = 7, minLevel = 16, icon = 134583,
    classes = { WARRIOR = true },
    stats = { ARMOR = 149, SPIRIT = 4, STAMINA = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2865:2668", recipeID = 2668,
        name = "Rough Bronze Leggings", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2866, name = "Rough Bronze Cuirass",
    slot = 5, minLevel = 18, icon = 132630,
    classes = { WARRIOR = true },
    stats = { ARMOR = 177, STAMINA = 8 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2866:2670", recipeID = 2670,
        name = "Rough Bronze Cuirass", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2867, name = "Rough Bronze Bracers",
    slot = 9, minLevel = 18, icon = 132604,
    classes = { WARRIOR = true },
    stats = { ARMOR = 77, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2867:2671", recipeID = 2671,
        name = "Rough Bronze Bracers", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2868, name = "Patterned Bronze Bracers",
    slot = 9, minLevel = 20, icon = 132606,
    classes = { WARRIOR = true },
    stats = { ARMOR = 80, STRENGTH = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2868:2672", recipeID = 2672,
        name = "Patterned Bronze Bracers", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2869, name = "Silvered Bronze Breastplate",
    slot = 5, minLevel = 21, icon = 132631,
    classes = { WARRIOR = true },
    stats = { ARMOR = 186, SPIRIT = 4, STAMINA = 5, STRENGTH = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2869:2673", recipeID = 2673,
        name = "Silvered Bronze Breastplate", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 2870, name = "Shining Silver Breastplate",
    slot = 5, minLevel = 24, icon = 132750,
    classes = { WARRIOR = true },
    stats = { ARMOR = 214, STAMINA = 6, STRENGTH = 14 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:2870:2675", recipeID = 2675,
        name = "Shining Silver Breastplate", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3469, name = "Copper Chain Boots",
    slot = 8, minLevel = 4, icon = 132535,
    classes = { WARRIOR = true },
    stats = { ARMOR = 74, STAMINA = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3469:3319", recipeID = 3319,
        name = "Copper Chain Boots", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3471, name = "Copper Chain Vest",
    slot = 5, minLevel = 5, icon = 132624,
    classes = { WARRIOR = true },
    stats = { ARMOR = 108, STRENGTH = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3471:3321", recipeID = 3321,
        name = "Copper Chain Vest", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3472, name = "Runed Copper Gauntlets",
    slot = 10, minLevel = 7, icon = 132938,
    classes = { WARRIOR = true },
    stats = { ARMOR = 77, STAMINA = 1, STRENGTH = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3472:3323", recipeID = 3323,
        name = "Runed Copper Gauntlets", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3473, name = "Runed Copper Pants",
    slot = 7, minLevel = 8, icon = 134583,
    classes = { WARRIOR = true },
    stats = { ARMOR = 113, STAMINA = 2, STRENGTH = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3473:3324", recipeID = 3324,
        name = "Runed Copper Pants", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3480, name = "Rough Bronze Shoulders",
    slot = 3, minLevel = 17, icon = 135036,
    classes = { WARRIOR = true },
    stats = { ARMOR = 130, STAMINA = 4, STRENGTH = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3480:3328", recipeID = 3328,
        name = "Rough Bronze Shoulders", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3481, name = "Silvered Bronze Shoulders",
    slot = 3, minLevel = 20, icon = 135040,
    classes = { WARRIOR = true },
    stats = { ARMOR = 137, SPIRIT = 3, STAMINA = 3, STRENGTH = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3481:3330", recipeID = 3330,
        name = "Silvered Bronze Shoulders", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3482, name = "Silvered Bronze Boots",
    slot = 8, minLevel = 21, icon = 132535,
    classes = { WARRIOR = true },
    stats = { ARMOR = 128, SPIRIT = 3, STAMINA = 4, STRENGTH = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3482:3331", recipeID = 3331,
        name = "Silvered Bronze Boots", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3483, name = "Silvered Bronze Gauntlets",
    slot = 10, minLevel = 22, icon = 132939,
    classes = { WARRIOR = true },
    stats = { ARMOR = 118, SPIRIT = 3, STAMINA = 4, STRENGTH = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3483:3333", recipeID = 3333,
        name = "Silvered Bronze Gauntlets", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3484, name = "Green Iron Boots",
    slot = 8, minLevel = 24, icon = 132535,
    classes = { WARRIOR = true },
    stats = { ARMOR = 134, STAMINA = 7, STRENGTH = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3484:3334", recipeID = 3334,
        name = "Green Iron Boots", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3485, name = "Green Iron Gauntlets",
    slot = 10, minLevel = 25, icon = 132939,
    classes = { WARRIOR = true },
    stats = { ARMOR = 124, STAMINA = 6, STRENGTH = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3485:3336", recipeID = 3336,
        name = "Green Iron Gauntlets", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3719, name = "Hillman's Cloak",
    slot = 15, minLevel = 25, icon = 133759,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { ARMOR = 21, SPELL_POWER = 5, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3719:3760", recipeID = 3760,
        name = "Hillman's Cloak", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3835, name = "Green Iron Bracers",
    slot = 9, minLevel = 28, icon = 132605,
    classes = { WARRIOR = true },
    stats = { ARMOR = 91, STAMINA = 5, STRENGTH = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3835:3501", recipeID = 3501,
        name = "Green Iron Bracers", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3836, name = "Green Iron Helm",
    slot = 1, minLevel = 29, icon = 133071,
    classes = { WARRIOR = true },
    stats = { ARMOR = 171, STAMINA = 11, STRENGTH = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3836:3502", recipeID = 3502,
        name = "Green Iron Helm", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3840, name = "Green Iron Shoulders",
    slot = 3, minLevel = 27, icon = 135040,
    classes = { WARRIOR = true },
    stats = { ARMOR = 153, STAMINA = 7, STRENGTH = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3840:3504", recipeID = 3504,
        name = "Green Iron Shoulders", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3841, name = "Golden Scale Shoulders",
    slot = 3, minLevel = 30, icon = 135040,
    classes = { WARRIOR = true },
    stats = { ARMOR = 160, STAMINA = 6, STRENGTH = 7 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3841:3505", recipeID = 3505,
        name = "Golden Scale Shoulders", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3842, name = "Green Iron Leggings",
    slot = 7, minLevel = 26, icon = 134585,
    classes = { WARRIOR = true },
    stats = { ARMOR = 176, STAMINA = 8, STRENGTH = 8 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3842:3506", recipeID = 3506,
        name = "Green Iron Leggings", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 3843, name = "Golden Scale Leggings",
    slot = 7, minLevel = 29, icon = 134584,
    classes = { WARRIOR = true },
    stats = { ARMOR = 184, STAMINA = 5, STRENGTH = 11 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:3843:3507", recipeID = 3507,
        name = "Golden Scale Leggings", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4237, name = "Handstitched Leather Belt",
    slot = 6, minLevel = 5, icon = 132493,
    classes = { ROGUE = true },
    stats = { ARMOR = 31, STRENGTH = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4237:3753", recipeID = 3753,
        name = "Handstitched Leather Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4239, name = "Embossed Leather Gloves",
    slot = 10, minLevel = 8, icon = 132939,
    classes = { ROGUE = true },
    stats = { AGILITY = 1, ARMOR = 41, STAMINA = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4239:3756", recipeID = 3756,
        name = "Embossed Leather Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4242, name = "Embossed Leather Pants",
    slot = 7, minLevel = 10, icon = 134582,
    classes = { ROGUE = true },
    stats = { ARMOR = 61, SPELL_POWER = 3, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4242:3759", recipeID = 3759,
        name = "Embossed Leather Pants", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4243, name = "Fine Leather Tunic",
    slot = 5, minLevel = 12, icon = 132724,
    classes = { ROGUE = true },
    stats = { AGILITY = 4, ARMOR = 73, STAMINA = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4243:3761", recipeID = 3761,
        name = "Fine Leather Tunic", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4244, name = "Hillman's Leather Vest",
    slot = 5, minLevel = 15, icon = 132725,
    classes = { ROGUE = true },
    stats = { ARMOR = 78, SPELL_POWER = 4, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4244:3762", recipeID = 3762,
        name = "Hillman's Leather Vest", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4246, name = "Fine Leather Belt",
    slot = 6, minLevel = 11, icon = 132493,
    classes = { ROGUE = true },
    stats = { AGILITY = 2, ARMOR = 40, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4246:3763", recipeID = 3763,
        name = "Fine Leather Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4247, name = "Hillman's Leather Gloves",
    slot = 10, minLevel = 24, icon = 132939,
    classes = { ROGUE = true },
    stats = { ARMOR = 57, SPELL_POWER = 5, STAMINA = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4247:3764", recipeID = 3764,
        name = "Hillman's Leather Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4249, name = "Dark Leather Belt",
    slot = 6, minLevel = 20, icon = 132492,
    classes = { ROGUE = true },
    stats = { AGILITY = 4, ARMOR = 48, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4249:3766", recipeID = 3766,
        name = "Dark Leather Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4250, name = "Hillman's Belt",
    slot = 6, minLevel = 20, icon = 132495,
    classes = { ROGUE = true },
    stats = { ARMOR = 48, SPELL_POWER = 4, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4250:3767", recipeID = 3767,
        name = "Hillman's Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4251, name = "Hillman's Shoulders",
    slot = 3, minLevel = 21, icon = 135039,
    classes = { ROGUE = true },
    stats = { ARMOR = 65, SPIRIT = 3, STAMINA = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4251:3768", recipeID = 3768,
        name = "Hillman's Shoulders", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4252, name = "Dark Leather Shoulders",
    slot = 3, minLevel = 23, icon = 135043,
    classes = { ROGUE = true },
    stats = { AGILITY = 7, ARMOR = 68 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4252:3769", recipeID = 3769,
        name = "Dark Leather Shoulders", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4253, name = "Toughened Leather Gloves",
    slot = 10, minLevel = 22, icon = 132958,
    classes = { ROGUE = true },
    stats = { AGILITY = 6, ARMOR = 61, STAMINA = 3, STRENGTH = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4253:3770", recipeID = 3770,
        name = "Toughened Leather Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4254, name = "Barbaric Gloves",
    slot = 10, minLevel = 25, icon = 132939,
    classes = { ROGUE = true },
    stats = { AGILITY = 4, ARMOR = 58, STAMINA = 5, STRENGTH = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4254:3771", recipeID = 3771,
        name = "Barbaric Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4255, name = "Green Leather Armor",
    slot = 5, minLevel = 26, icon = 132723,
    classes = { ROGUE = true },
    stats = { AGILITY = 8, ARMOR = 95, INTELLECT = 8 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4255:3772", recipeID = 3772,
        name = "Green Leather Armor", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4256, name = "Guardian Armor",
    slot = 5, minLevel = 30, icon = 132723,
    classes = { ROGUE = true },
    stats = { ARMOR = 102, INTELLECT = 10, SPELL_POWER = 9 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4256:3773", recipeID = 3773,
        name = "Guardian Armor", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4257, name = "Green Leather Belt",
    slot = 6, minLevel = 27, icon = 132506,
    classes = { ROGUE = true },
    stats = { AGILITY = 6, ARMOR = 54, INTELLECT = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4257:3774", recipeID = 3774,
        name = "Green Leather Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4258, name = "Guardian Belt",
    slot = 6, minLevel = 29, icon = 132492,
    classes = { ROGUE = true },
    stats = { ARMOR = 56, INTELLECT = 7, SPELL_POWER = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4258:3775", recipeID = 3775,
        name = "Guardian Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4307, name = "Heavy Linen Gloves",
    slot = 10, minLevel = 5, icon = 132939,
    classes = { PRIEST = true },
    stats = { ARMOR = 12, SPELL_POWER = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4307:3840", recipeID = 3840,
        name = "Heavy Linen Gloves", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4308, name = "Green Linen Bracers",
    slot = 9, minLevel = 7, icon = 132611,
    classes = { PRIEST = true },
    stats = { ARMOR = 10, SPIRIT = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4308:3841", recipeID = 3841,
        name = "Green Linen Bracers", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4309, name = "Handstitched Linen Britches",
    slot = 7, minLevel = 9, icon = 134587,
    classes = { PRIEST = true },
    stats = { ARMOR = 23, INTELLECT = 2, SPELL_POWER = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4309:3842", recipeID = 3842,
        name = "Handstitched Linen Britches", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4310, name = "Heavy Woolen Gloves",
    slot = 10, minLevel = 12, icon = 132939,
    classes = { PRIEST = true },
    stats = { ARMOR = 19, INTELLECT = 2, SPELL_POWER = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4310:3843", recipeID = 3843,
        name = "Heavy Woolen Gloves", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4311, name = "Heavy Woolen Cloak",
    slot = 15, minLevel = 16, icon = 133766,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { ARMOR = 17, SPELL_POWER = 4, SPIRIT = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4311:3844", recipeID = 3844,
        name = "Heavy Woolen Cloak", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4312, name = "Soft-soled Linen Boots",
    slot = 8, minLevel = 11, icon = 132543,
    classes = { PRIEST = true },
    stats = { ARMOR = 20, SPELL_POWER = 2, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4312:3845", recipeID = 3845,
        name = "Soft-soled Linen Boots", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4313, name = "Red Woolen Boots",
    slot = 8, minLevel = 15, icon = 132543,
    classes = { PRIEST = true },
    stats = { ARMOR = 23, SPELL_POWER = 4, SPIRIT = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4313:3847", recipeID = 3847,
        name = "Red Woolen Boots", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4314, name = "Double-Stitched Woolen Shoulders",
    slot = 3, minLevel = 17, icon = 135037,
    classes = { PRIEST = true },
    stats = { ARMOR = 27, SPELL_POWER = 4, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4314:3848", recipeID = 3848,
        name = "Double-stitched Woolen Shoulders", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4315, name = "Reinforced Woolen Shoulders",
    slot = 3, minLevel = 19, icon = 135040,
    classes = { PRIEST = true },
    stats = { ARMOR = 28, INTELLECT = 4, SPELL_POWER = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4315:3849", recipeID = 3849,
        name = "Reinforced Woolen Shoulders", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4316, name = "Heavy Woolen Pants",
    slot = 7, minLevel = 17, icon = 134581,
    classes = { PRIEST = true },
    stats = { ARMOR = 31, SPELL_POWER = 3, SPIRIT = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4316:3850", recipeID = 3850,
        name = "Heavy Woolen Pants", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4318, name = "Gloves of Meditation",
    slot = 10, minLevel = 21, icon = 132939,
    classes = { PRIEST = true },
    stats = { ARMOR = 25, SPELL_POWER = 5, SPIRIT = 7 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4318:3852", recipeID = 3852,
        name = "Gloves of Meditation", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4320, name = "Spidersilk Boots",
    slot = 8, minLevel = 20, icon = 132539,
    classes = { PRIEST = true },
    stats = { ARMOR = 29, INTELLECT = 4, SPELL_POWER = 7, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4320:3855", recipeID = 3855,
        name = "Spidersilk Boots", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4321, name = "Spider Silk Slippers",
    slot = 8, minLevel = 23, icon = 132537,
    classes = { PRIEST = true },
    stats = { ARMOR = 29, SPELL_POWER = 3, SPIRIT = 7 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4321:3856", recipeID = 3856,
        name = "Spider Silk Slippers", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4322, name = "Enchanter's Cowl",
    slot = 1, minLevel = 28, icon = 133133,
    classes = { PRIEST = true },
    stats = { ARMOR = 37, INTELLECT = 10, SPELL_POWER = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4322:3857", recipeID = 3857,
        name = "Enchanter's Cowl", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4325, name = "Boots of the Enchanter",
    slot = 8, minLevel = 30, icon = 132539,
    classes = { PRIEST = true },
    stats = { ARMOR = 32, SPELL_POWER = 5, SPIRIT = 8 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4325:3860", recipeID = 3860,
        name = "Boots of the Enchanter", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4343, name = "Brown Linen Pants",
    slot = 7, minLevel = 5, icon = 134586,
    classes = { PRIEST = true },
    stats = { ARMOR = 17, SPELL_POWER = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4343:3914", recipeID = 3914,
        name = "Brown Linen Pants", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4455, name = "Raptor Hide Harness",
    slot = 5, minLevel = 28, icon = 132719,
    classes = { ROGUE = true },
    stats = { ARMOR = 98, STAMINA = 13 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4455:4096", recipeID = 4096,
        name = "Raptor Hide Harness", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 4456, name = "Raptor Hide Belt",
    slot = 6, minLevel = 28, icon = 132491,
    classes = { ROGUE = true },
    stats = { ARMOR = 55, STAMINA = 6, STRENGTH = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:4456:4097", recipeID = 4097,
        name = "Raptor Hide Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5542, name = "Pearl-clasped Cloak",
    slot = 15, minLevel = 14, icon = 133763,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { ARMOR = 16, INTELLECT = 3, SPELL_POWER = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5542:6521", recipeID = 6521,
        name = "Pearl-clasped Cloak", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5766, name = "Lesser Wizard's Robe",
    slot = 5, minLevel = 22, icon = 132658,
    classes = { PRIEST = true },
    stats = { ARMOR = 41, INTELLECT = 8, SPELL_POWER = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5766:6690", recipeID = 6690,
        name = "Lesser Wizard's Robe", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5770, name = "Robes of Arcana",
    slot = 5, minLevel = 25, icon = 132670,
    classes = { PRIEST = true },
    stats = { ARMOR = 43, SPELL_POWER = 8, SPIRIT = 7 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5770:6692", recipeID = 6692,
        name = "Robes of Arcana", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5780, name = "Murloc Scale Belt",
    slot = 6, minLevel = 13, icon = 132491,
    classes = { ROGUE = true },
    stats = { AGILITY = 3, ARMOR = 42, STRENGTH = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5780:6702", recipeID = 6702,
        name = "Murloc Scale Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5781, name = "Murloc Scale Breastplate",
    slot = 5, minLevel = 14, icon = 132634,
    classes = { ROGUE = true },
    stats = { AGILITY = 3, ARMOR = 76, STRENGTH = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5781:6703", recipeID = 6703,
        name = "Murloc Scale Breastplate", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5782, name = "Thick Murloc Armor",
    slot = 5, minLevel = 29, icon = 132634,
    classes = { ROGUE = true },
    stats = { ARMOR = 100, STAMINA = 8, STRENGTH = 9 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5782:6704", recipeID = 6704,
        name = "Thick Murloc Armor", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5957, name = "Handstitched Leather Vest",
    slot = 5, minLevel = 3, icon = 132760,
    classes = { ROGUE = true },
    stats = { AGILITY = 1, ARMOR = 55 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5957:7126", recipeID = 7126,
        name = "Handstitched Leather Vest", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5958, name = "Fine Leather Pants",
    slot = 7, minLevel = 16, icon = 134582,
    classes = { ROGUE = true },
    stats = { ARMOR = 69, INTELLECT = 5, SPIRIT = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5958:7133", recipeID = 7133,
        name = "Fine Leather Pants", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5961, name = "Dark Leather Pants",
    slot = 7, minLevel = 18, icon = 134589,
    classes = { ROGUE = true },
    stats = { AGILITY = 8, ARMOR = 72 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5961:7135", recipeID = 7135,
        name = "Dark Leather Pants", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5962, name = "Guardian Pants",
    slot = 7, minLevel = 27, icon = 134582,
    classes = { ROGUE = true },
    stats = { ARMOR = 85, INTELLECT = 8, SPELL_POWER = 8 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5962:7147", recipeID = 7147,
        name = "Guardian Pants", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5963, name = "Barbaric Leggings",
    slot = 7, minLevel = 29, icon = 134592,
    classes = { ROGUE = true },
    stats = { AGILITY = 7, ARMOR = 87, STAMINA = 7, STRENGTH = 7 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5963:7149", recipeID = 7149,
        name = "Barbaric Leggings", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 5964, name = "Barbaric Shoulders",
    slot = 3, minLevel = 30, icon = 135039,
    classes = { ROGUE = true },
    stats = { AGILITY = 5, ARMOR = 76, STAMINA = 6, STRENGTH = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:5964:7151", recipeID = 7151,
        name = "Barbaric Shoulders", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6238, name = "Brown Linen Robe",
    slot = 5, minLevel = 5, icon = 132662,
    classes = { PRIEST = true },
    stats = { ARMOR = 19, SPIRIT = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6238:7623", recipeID = 7623,
        name = "Brown Linen Robe", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6239, name = "Red Linen Vest",
    slot = 5, minLevel = 7, icon = 132681,
    classes = { PRIEST = true },
    stats = { ARMOR = 23, INTELLECT = 2, SPELL_POWER = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6239:7629", recipeID = 7629,
        name = "Red Linen Vest", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6240, name = "Blue Linen Vest",
    slot = 5, minLevel = 7, icon = 132678,
    classes = { PRIEST = true },
    stats = { ARMOR = 23, SPELL_POWER = 1, SPIRIT = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6240:7630", recipeID = 7630,
        name = "Blue Linen Vest", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6241, name = "White Linen Robe",
    slot = 5, minLevel = 5, icon = 132645,
    classes = { PRIEST = true },
    stats = { ARMOR = 19, INTELLECT = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6241:7624", recipeID = 7624,
        name = "White Linen Robe", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6242, name = "Blue Linen Robe",
    slot = 5, minLevel = 9, icon = 132664,
    classes = { PRIEST = true },
    stats = { ARMOR = 26, SPELL_POWER = 2, SPIRIT = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6242:7633", recipeID = 7633,
        name = "Blue Linen Robe", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6243, name = "Green Woolen Robe",
    slot = 5, minLevel = 13, icon = 132663,
    classes = { PRIEST = true },
    stats = { ARMOR = 32, INTELLECT = 3, SPELL_POWER = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6243:7636", recipeID = 7636,
        name = "Green Woolen Robe", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6263, name = "Blue Overalls",
    slot = 5, minLevel = 15, icon = 135017,
    classes = { PRIEST = true },
    stats = { ARMOR = 34, STAMINA = 4, STRENGTH = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6263:7639", recipeID = 7639,
        name = "Blue Overalls", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6264, name = "Greater Adept's Robe",
    slot = 5, minLevel = 18, icon = 132665,
    classes = { PRIEST = true },
    stats = { ARMOR = 37, INTELLECT = 2, SPELL_POWER = 1, SPIRIT = 7 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6264:7643", recipeID = 7643,
        name = "Greater Adept's Robe", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6350, name = "Rough Bronze Boots",
    slot = 8, minLevel = 13, icon = 132535,
    classes = { WARRIOR = true },
    stats = { ARMOR = 111, STAMINA = 3, STRENGTH = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6350:7817", recipeID = 7817,
        name = "Rough Bronze Boots", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6466, name = "Deviate Scale Cloak",
    slot = 15, minLevel = 13, icon = 134305,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { AGILITY = 2, ARMOR = 16, STAMINA = 2 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6466:7953", recipeID = 7953,
        name = "Deviate Scale Cloak", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6467, name = "Deviate Scale Gloves",
    slot = 10, minLevel = 16, icon = 132939,
    classes = { ROGUE = true },
    stats = { AGILITY = 3, ARMOR = 49, STAMINA = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6467:7954", recipeID = 7954,
        name = "Deviate Scale Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6468, name = "Deviate Scale Belt",
    slot = 6, minLevel = 18, icon = 132498,
    classes = { ROGUE = true },
    stats = { AGILITY = 5, ARMOR = 51, STAMINA = 6, STRENGTH = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6468:7955", recipeID = 7955,
        name = "Deviate Scale Belt", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6709, name = "Moonglow Vest",
    slot = 5, minLevel = 13, icon = 132724,
    classes = { ROGUE = true },
    stats = { ARMOR = 74, INTELLECT = 3, SPELL_POWER = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6709:8322", recipeID = 8322,
        name = "Moonglow Vest", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6730, name = "Ironforge Chain",
    slot = 5, minLevel = 11, icon = 132624,
    classes = { WARRIOR = true },
    stats = { ARMOR = 151, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6730:8366", recipeID = 8366,
        name = "Ironforge Chain", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 6787, name = "White Woolen Dress",
    slot = 5, minLevel = 17, icon = 135016,
    classes = { PRIEST = true },
    stats = { ARMOR = 36, SPIRIT = 4, STAMINA = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:6787:8467", recipeID = 8467,
        name = "White Woolen Dress", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7049, name = "Truefaith Gloves",
    slot = 10, minLevel = 25, icon = 132950,
    classes = { PRIEST = true },
    stats = { ARMOR = 27, HEALING = 15, INTELLECT = 3, SPELL_POWER = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7049:8782", recipeID = 8782,
        name = "Truefaith Gloves", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7050, name = "Silk Headband",
    slot = 1, minLevel = 27, icon = 133693,
    classes = { PRIEST = true },
    stats = { ARMOR = 36, SPELL_POWER = 9, STAMINA = 8 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7050:8762", recipeID = 8762,
        name = "Silk Headband", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7051, name = "Earthen Vest",
    slot = 5, minLevel = 29, icon = 135008,
    classes = { PRIEST = true },
    stats = { ARMOR = 46, SPIRIT = 10, STAMINA = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7051:8764", recipeID = 8764,
        name = "Earthen Vest", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7055, name = "Crimson Silk Belt",
    slot = 6, minLevel = 30, icon = 132493,
    classes = { PRIEST = true },
    stats = { ARMOR = 26, INTELLECT = 7, SPELL_POWER = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7055:8772", recipeID = 8772,
        name = "Crimson Silk Belt", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7065, name = "Green Silk Armor",
    slot = 5, minLevel = 28, icon = 132647,
    classes = { PRIEST = true },
    stats = { ARMOR = 45, INTELLECT = 13, SPELL_POWER = 9 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7065:8784", recipeID = 8784,
        name = "Green Silk Armor", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7280, name = "Rugged Leather Pants",
    slot = 7, minLevel = 6, icon = 134582,
    classes = { ROGUE = true },
    stats = { ARMOR = 51, STAMINA = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7280:9064", recipeID = 9064,
        name = "Rugged Leather Pants", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7281, name = "Light Leather Bracers",
    slot = 9, minLevel = 9, icon = 132603,
    classes = { ROGUE = true },
    stats = { AGILITY = 1, ARMOR = 30, STRENGTH = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7281:9065", recipeID = 9065,
        name = "Light Leather Bracers", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7282, name = "Light Leather Pants",
    slot = 7, minLevel = 14, icon = 134582,
    classes = { ROGUE = true },
    stats = { AGILITY = 5, ARMOR = 66, STAMINA = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7282:9068", recipeID = 9068,
        name = "Light Leather Pants", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7283, name = "Black Whelp Cloak",
    slot = 15, minLevel = 15, icon = 134305,
    classes = { PRIEST = true, ROGUE = true, WARRIOR = true },
    stats = { ARMOR = 17, SPELL_POWER = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7283:9070", recipeID = 9070,
        name = "Black Whelp Cloak", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7285, name = "Nimble Leather Gloves",
    slot = 10, minLevel = 19, icon = 132939,
    classes = { ROGUE = true },
    stats = { AGILITY = 4, ARMOR = 52, STAMINA = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7285:9074", recipeID = 9074,
        name = "Nimble Leather Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7352, name = "Earthen Leather Shoulders",
    slot = 3, minLevel = 22, icon = 135037,
    classes = { ROGUE = true },
    stats = { ARMOR = 67, STAMINA = 7 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7352:9147", recipeID = 9147,
        name = "Earthen Leather Shoulders", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7358, name = "Pilferer's Gloves",
    slot = 10, minLevel = 23, icon = 132939,
    classes = { ROGUE = true },
    stats = { AGILITY = 8, ARMOR = 56 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7358:9148", recipeID = 9148,
        name = "Pilferer's Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7359, name = "Heavy Earthen Gloves",
    slot = 10, minLevel = 24, icon = 132957,
    classes = { ROGUE = true },
    stats = { ARMOR = 57, ATTACK_POWER = 16 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7359:9149", recipeID = 9149,
        name = "Heavy Earthen Gloves", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7373, name = "Dusky Leather Leggings",
    slot = 7, minLevel = 28, icon = 134587,
    classes = { ROGUE = true },
    stats = { AGILITY = 13, ARMOR = 86 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7373:9195", recipeID = 9195,
        name = "Dusky Leather Leggings", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7374, name = "Dusky Leather Armor",
    slot = 5, minLevel = 30, icon = 132718,
    classes = { ROGUE = true },
    stats = { AGILITY = 14, ARMOR = 102 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7374:9196", recipeID = 9196,
        name = "Dusky Leather Armor", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7913, name = "Barbaric Iron Shoulders",
    slot = 3, minLevel = 27, icon = 135054,
    classes = { WARRIOR = true },
    stats = { AGILITY = 6, ARMOR = 153, STRENGTH = 6 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7913:9811", recipeID = 9811,
        name = "Barbaric Iron Shoulders", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7914, name = "Barbaric Iron Breastplate",
    slot = 5, minLevel = 27, icon = 132636,
    classes = { WARRIOR = true },
    stats = { ARMOR = 204, STRENGTH = 12 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7914:9813", recipeID = 9813,
        name = "Barbaric Iron Breastplate", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 7915, name = "Barbaric Iron Helm",
    slot = 1, minLevel = 30, icon = 133127,
    classes = { WARRIOR = true },
    stats = { AGILITY = 9, ARMOR = 173, STRENGTH = 9 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:7915:9814", recipeID = 9814,
        name = "Barbaric Iron Helm", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 10047, name = "Simple Kilt",
    slot = 7, minLevel = 10, icon = 134591,
    classes = { PRIEST = true },
    stats = { ARMOR = 24, SPELL_POWER = 2, STAMINA = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:10047:12046", recipeID = 12046,
        name = "Simple Kilt", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 10048, name = "Colorful Kilt",
    slot = 7, minLevel = 14, icon = 134582,
    classes = { PRIEST = true },
    stats = { ARMOR = 29, SPELL_POWER = 5, SPIRIT = 5 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:10048:12047", recipeID = 12047,
        name = "Colorful Kilt", profession = "Tailoring",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 10421, name = "Rough Copper Vest",
    slot = 5, minLevel = 2, icon = 132624,
    classes = { WARRIOR = true },
    stats = { ARMOR = 108, STAMINA = 1 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:10421:12260", recipeID = 12260,
        name = "Rough Copper Vest", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 10423, name = "Silvered Bronze Leggings",
    slot = 7, minLevel = 26, icon = 134584,
    classes = { WARRIOR = true },
    stats = { ARMOR = 176, SPIRIT = 6, STAMINA = 6, STRENGTH = 7 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:10423:12259", recipeID = 12259,
        name = "Silvered Bronze Leggings", profession = "Blacksmithing",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 18948, name = "Barbaric Bracers",
    slot = 9, minLevel = 27, icon = 132614,
    classes = { ROGUE = true },
    stats = { AGILITY = 4, ARMOR = 47, STAMINA = 6, STRENGTH = 4 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:18948:23399", recipeID = 23399,
        name = "Barbaric Bracers", profession = "Leatherworking",
      },
    },
  },
  {
    _status = "provisional",
    itemID = 20575, name = "Black Whelp Tunic",
    slot = 5, minLevel = 15, icon = 132686,
    classes = { ROGUE = true },
    stats = { ARMOR = 78, INTELLECT = 5, SPELL_POWER = 3 },
    routes = {
      {
        _status = "provisional", kind = "craft",
        key = "craft:20575:24940", recipeID = 24940,
        name = "Black Whelp Tunic", profession = "Leatherworking",
      },
    },
  },
}

ns.Data.GearCatalog = {
  _status = "provisional",
  source = "https://foreverdb.net/data/items.json",
  recipeSource = "https://foreverdb.net/data/crafting/{shard}.json",
  sourceBuild = "1.60.1.70205",
  retrievedAt = "2026-10-05",
  sourceSha256 = "aba322ef0f01ccf5c73c1c99485bdcd27cc9657e310db0e42a45f1846319e521",
  PRIEST = {
    items[4], items[6], items[10], items[12], items[13], items[14], items[15], items[16],
    items[17], items[18], items[19], items[41], items[65], items[66], items[67], items[68],
    items[69], items[70], items[71], items[72], items[73], items[74], items[75], items[76],
    items[77], items[78], items[79], items[80], items[83], items[84], items[85], items[95],
    items[96], items[97], items[98], items[99], items[100], items[101], items[102], items[104],
    items[109], items[110], items[111], items[112], items[113], items[114], items[118], items[128],
    items[129],
  },
  ROGUE = {
    items[1], items[2], items[3], items[4], items[5], items[6], items[7], items[8],
    items[9], items[10], items[11], items[15], items[18], items[41], items[48], items[49],
    items[50], items[51], items[52], items[53], items[54], items[55], items[56], items[57],
    items[58], items[59], items[60], items[61], items[62], items[63], items[64], items[69],
    items[81], items[82], items[83], items[86], items[87], items[88], items[89], items[90],
    items[91], items[92], items[93], items[94], items[104], items[105], items[106], items[107],
    items[115], items[116], items[117], items[118], items[119], items[120], items[121], items[122],
    items[123], items[124], items[132], items[133],
  },
  WARRIOR = {
    items[4], items[6], items[10], items[15], items[18], items[20], items[21], items[22],
    items[23], items[24], items[25], items[26], items[27], items[28], items[29], items[30],
    items[31], items[32], items[33], items[34], items[35], items[36], items[37], items[38],
    items[39], items[40], items[41], items[42], items[43], items[44], items[45], items[46],
    items[47], items[69], items[83], items[103], items[104], items[108], items[118], items[125],
    items[126], items[127], items[130], items[131],
  },
}
