#!/usr/bin/env python3
"""Generate compact Lua talent rules from the dated structural snapshot.

No tooltip text or source-site code is embedded. Source metadata is retained;
these imported rules remain provisional until confirmed by beta captures.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'data/talents/catalog.json'
OUTPUT = ROOT / 'Battleplan/Data/TalentRules.lua'


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def render(data):
    if data.get('_status') != 'provisional':
        raise ValueError('External snapshots must remain provisional')
    lines = ['-- Generated by tools/import_talent_catalog.py; do not edit.',
             '-- Structural facts only; external snapshot, not confirmed live server rules.',
             'local _, ns = ...', '', 'ns.Data.TalentRules = {', '  _status = "provisional",']
    for key in ('source', 'sourceBuild', 'retrievedAt', 'sourceSha256'):
        lines.append(f'  {key} = {quote(data[key])},')
    for cls, rules in sorted(data['classes'].items()):
        ids = {r['id']: name for name, r in rules.items()}
        if len(ids) != len(rules):
            raise ValueError(f'{cls}: duplicate talent IDs')
        lines.append(f'  {cls} = {{')
        for name, rule in sorted(rules.items()):
            if rule['maxRank'] < 1 or rule['minLevel'] < 10:
                raise ValueError(f'{cls}: invalid ranks/level for {name}')
            lines.append(f'    [{quote(name)}] = {{')
            for key in ('id', 'spellID', 'tree', 'maxRank', 'minLevel'):
                value = quote(rule[key]) if isinstance(rule[key], str) else rule[key]
                lines.append(f'      {key} = {value},')
            lines.append(f'      treePoints = {rule["gate"][0] if rule["gate"] else 0},')
            lines.append('      requires = {')
            for prerequisite in rule['requires']:
                talent_id, rank = prerequisite[:2]
                if talent_id not in ids or rank > rules[ids[talent_id]]['maxRank']:
                    raise ValueError(f'{cls}: invalid prerequisite for {name}')
                extra = ''.join(f', {v}' for v in prerequisite[2:])
                lines.append(f'        {{ {quote(ids[talent_id])}, {rank}{extra} }},')
            lines.extend(['      },', '    },'])
        lines.append('  },')
    lines.extend(['}', ''])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if generated Lua is stale')
    args = parser.parse_args()
    generated = render(json.loads(SOURCE.read_text(encoding='utf-8')))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != generated:
            parser.exit(1, 'TalentRules.lua is stale; run tools/import_talent_catalog.py\n')
    else:
        OUTPUT.write_text(generated, encoding='utf-8')
    print('talent catalog: ok')


if __name__ == '__main__':
    main()
