#!/usr/bin/env python3
"""Import complete Warrior rank tooltips as observed text, never numeric combat coefficients."""
import argparse
import hashlib
import json
from pathlib import Path
from import_spell_catalog import lua, text

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'data/probe/2026-10-05-warrior-12-talent-effects.json'
OUTPUT = ROOT / 'Battleplan/Data/WARRIOR/TalentEffects.lua'


def catalog(data):
    captures = [c for c in data.get('captures', {}).get('talents', [])
                if c.get('who', {}).get('class') == 'WARRIOR' and
                c.get('data', {}).get('tooltipReadsComplete') is True]
    if not captures:
        raise ValueError('No complete Warrior rank tooltip capture')
    cap = max(captures, key=lambda c: c['at'])
    snapshot = cap['data']
    if snapshot.get('complete') is not True or snapshot.get('tooltipFailures') != 0:
        raise ValueError('Capture has structural or tooltip failures')
    records = {}
    count = 0
    for node in snapshot['nodes']:
        if node.get('info', {}).get('status') != 'ok' or type(node.get('nodeID')) is not int:
            raise ValueError('Unreadable node metadata')
        for entry in node['entries']:
            name = entry.get('spell', {}).get('name')
            info = entry['info']
            definition = entry['definition']
            if info['status'] != 'ok' or definition['status'] != 'ok':
                raise ValueError('Unreadable entry metadata')
            maximum = info['values'][0]['maxRanks']
            sid = definition['values'][0]['spellID']
            if not text(name) or not name or name in records or type(maximum) is not int or not 1 <= maximum <= 100:
                raise ValueError('Invalid or duplicate talent')
            if type(sid) is not int or sid <= 0 or type(entry.get('entryID')) is not int:
                raise ValueError('Invalid or duplicate talent')
            ranks = {}
            for tooltip in entry.get('tooltips', []):
                rank = tooltip.get('rank')
                if type(rank) is not int or rank < 1 or rank > maximum or rank in ranks:
                    raise ValueError('Invalid or duplicate rank')
                lines = []
                if tooltip.get('status') != 'ok':
                    raise ValueError('Unreadable rank tooltip')
                for line in tooltip.get('lines', []):
                    for field in ('leftText', 'rightText'):
                        value = line.get(field)
                        if value is not None:
                            if not text(value):
                                raise ValueError('Unreadable tooltip line')
                            if value:
                                lines.append(value)
                if not lines:
                    raise ValueError('Empty rank tooltip')
                ranks[rank] = '\n'.join(lines)
            if set(ranks) != set(range(1, maximum + 1)):
                raise ValueError('Missing talent ranks')
            count += len(ranks)
            records[name] = {'nodeID': node['nodeID'], 'entryID': entry['entryID'],
                             'spellID': sid, 'ranks': [ranks[i] for i in range(1, maximum + 1)]}
    if count != snapshot['tooltipExpected'] or count != snapshot['tooltipReads'] or not records:
        raise ValueError('Tooltip totals do not match the entries')
    return cap, records


def string_lines(value, indent):
    chunks = [value[i:i + 64] for i in range(0, len(value), 64)]
    return [indent + lua(chunk) + (' ..' if i < len(chunks) - 1 else ',')
            for i, chunk in enumerate(chunks)]


def render(raw, source):
    data = json.loads(raw)
    cap, records = catalog(data)
    builds = {tuple(c['data']['build'][:2]) for c in data.get('captures', {}).get('env', [])
              if c.get('data', {}).get('build')}
    if len(builds) != 1:
        raise ValueError('Expected one client build')
    version, build = next(iter(builds))
    lines = ['-- Generated by tools/import_talent_effects.py; do not edit.',
             '-- Verified text at the captured level/build. Active ability numbers may scale with level or gear.',
             'local _, ns = ...', '', 'ns.Data.WARRIOR.TalentEffects = {', '  _status = "verified",',
             f'  source = {lua(source)},', f'  sourceSha256 = {lua(hashlib.sha256(raw).hexdigest())},',
             f'  sourceBuild = {lua(str(version) + "." + str(build))},',
             f'  capturedAt = {lua(cap["at"])},', f'  observedAtLevel = {cap["who"]["level"]},']
    for name, row in sorted(records.items()):
        lines.extend([f'  [{lua(name)}] = {{', f'    nodeID = {row["nodeID"]},',
                      f'    entryID = {row["entryID"]},', f'    spellID = {row["spellID"]},', '    ranks = {'])
        for rank in row['ranks']:
            lines.extend(string_lines(rank, '      '))
        lines.extend(['    },', '  },'])
    return '\n'.join(lines + ['}', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = render(SOURCE.read_bytes(), str(SOURCE.relative_to(ROOT)))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != generated:
            parser.exit(1, 'TalentEffects.lua is stale; run tools/import_talent_effects.py\n')
    else:
        OUTPUT.write_text(generated, encoding='utf-8')
    print('Warrior talent effects: ok')


if __name__ == '__main__':
    main()
