#!/usr/bin/env python3
"""Generate a compact, dated Warrior spell catalog from an unchanged probe export.

Known-at-level is evidence of possession, never a trainer level. Cooldown duration
is intentionally excluded: a ready spell's capture reports zero, not its base cooldown.
"""
import argparse
import hashlib
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'data/probe/2026-10-05-warrior-12-followup.json'
OUTPUT = ROOT / 'Battleplan/Data/WARRIOR/Spells.lua'


def text(value):
    return isinstance(value, str) and not (value.startswith('<') and value.endswith('>'))


def number(value):
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value)


def lua(value):
    if isinstance(value, str):
        # JSON's Unicode/control escapes are not Lua 5.1 escapes.
        return '"' + ''.join('\\%03d' % ord(c) if ord(c) < 32 else
                             '\\' + c if c in '\\"' else c for c in value) + '"'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, list):
        return '{ ' + ', '.join(lua(v) for v in value) + ' }'
    if isinstance(value, dict):
        return '{ ' + ', '.join(f'{k} = {lua(v)}' for k, v in value.items()) + ' }'
    return str(value)


def catalog(data):
    records = {}
    for cap in sorted(data.get('captures', {}).get('spells', []), key=lambda c: c['at']):
        who = cap.get('who', {})
        if who.get('class') != 'WARRIOR' or not number(who.get('level')):
            continue
        for spell in cap.get('data', {}).get('spells', []):
            sid, name = spell.get('spellID'), spell.get('name')
            if not isinstance(sid, int) or isinstance(sid, bool) or sid <= 0 or not text(name) or not name:
                continue
            previous = records.get(sid)
            if previous and previous['name'] != name:
                raise ValueError(f'Conflicting names for spell {sid}')
            row = {'name': name, 'observedAtLevel': min(who['level'], previous['observedAtLevel'])
                   if previous else who['level']}
            sub = spell.get('subName')
            rank = re.fullmatch(r'Rank (\d+)', sub) if text(sub) else None
            if rank:
                row['rank'] = int(rank[1])
            for field in ('tab', 'description'):
                if text(spell.get(field)):
                    row[field] = spell[field]
            for field in ('castTime', 'minRange', 'maxRange'):
                if number(spell.get(field)):
                    row[field] = spell[field]
            for field in ('isPassive',):
                if isinstance(spell.get(field), bool):
                    row[field] = spell[field]
            costs = []
            for cost in spell.get('costs', []):
                if number(cost.get('cost')) and number(cost.get('type')):
                    c = {'type': cost['type'], 'cost': cost['cost']}
                    if text(cost.get('name')):
                        c['name'] = cost['name']
                    if number(cost.get('costPercent')):
                        c['costPercent'] = cost['costPercent']
                    costs.append(c)
            if costs:
                row['costs'] = costs
            row['capturedAt'] = cap['at']
            records[sid] = row
    if not records:
        raise ValueError('No readable Warrior spell records')
    return records


def render(raw, source):
    data = json.loads(raw)
    builds = {tuple(c['data']['build'][:2]) for c in data.get('captures', {}).get('env', [])
              if c.get('data', {}).get('build')}
    if len(builds) != 1:
        raise ValueError('Expected one client build in the export')
    version, build = next(iter(builds))
    lines = ['-- Generated by tools/import_spell_catalog.py; do not edit.',
             '-- Verified observations for this capture/build; not learning levels or base cooldowns.',
             'local _, ns = ...', '', 'ns.Data.WARRIOR.Spells = {', '  _status = "verified",',
             f'  source = {lua(source)},', f'  sourceBuild = {lua(str(version) + "." + str(build))},',
             f'  sourceSha256 = {lua(hashlib.sha256(raw).hexdigest())},']
    for sid, row in sorted(catalog(data).items()):
        lines.append(f'  [{sid}] = {{')
        for key, value in row.items():
            rendered = lua(value)
            if isinstance(value, str) and len(f'    {key} = {rendered},') > 140:
                chunks = [value[i:i + 80] for i in range(0, len(value), 80)]
                lines.append(f'    {key} = ' + lua(chunks[0]) + ' ..')
                for i, chunk in enumerate(chunks[1:]):
                    lines.append('      ' + lua(chunk) + (' ..' if i < len(chunks) - 2 else ','))
            else:
                lines.append(f'    {key} = {rendered},')
        lines.append('  },')
    return '\n'.join(lines + ['}', ''])


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args(argv)
    generated = render(SOURCE.read_bytes(), str(SOURCE.relative_to(ROOT)))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != generated:
            parser.exit(1, 'Spells.lua is stale; run tools/import_spell_catalog.py\n')
    else:
        OUTPUT.write_text(generated, encoding='utf-8')
    print('Warrior spell catalog: ok')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
