#!/usr/bin/env python3
"""Generate a provisional, tradeable crafted-armor catalog from client-derived facts."""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'data/gear/client-crafting.json'
OUTPUT = ROOT / 'data/gear/starter-catalog.lua'
SLOTS = {1: 1, 3: 3, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 16: 15, 20: 5}
ARMOR_CLASS = {1: 'PRIEST', 2: 'ROGUE', 3: 'WARRIOR'}
PROFESSIONS = {'blacksmithing': 'Blacksmithing', 'leatherworking': 'Leatherworking', 'tailoring': 'Tailoring'}
STATS = {1: ('HEALTH', 1), 3: ('AGILITY', 1), 4: ('STRENGTH', 1), 5: ('INTELLECT', 1),
         6: ('SPIRIT', 1), 7: ('STAMINA', 1), 12: ('DEFENSE', 1), 31: ('HIT_PCT', 10),
         32: ('CRIT_PCT', 14), 36: ('HASTE_PCT', 10), 37: ('EXPERTISE_PCT', 10),
         38: ('ATTACK_POWER', 1), 41: ('HEALING', 1), 42: ('SPELL_POWER', 1),
         43: ('MP5', 1), 45: ('SPELL_POWER', 1)}


def eligible(item):
    """Keep a small ordinary-armor cohort; unsupported restrictions/effects stay out."""
    return (type(item.get('id')) is int and item['id'] > 0
            and type(item.get('ic')) is int and item['ic'] > 0
            and type(item.get('ar')) is int and item['ar'] > 0
            and isinstance(item.get('n'), str) and bool(item['n'])
            and item.get('src') == 'f' and item.get('c') == 4 and item.get('sc') in ARMOR_CLASS
            and item.get('inv') in SLOTS and item.get('b') == 2 and item.get('q') in (2, 3)
            and type(item.get('rl')) is int and 0 <= max(item['rl'], item.get('el', 0)) <= 30
            and all(not item.get(k) for k in ('sp', 'rs', 'spec', 'bar', 'new'))
            and bool(item.get('st')) and all(stat in STATS for stat, _ in item['st']))


def snapshot(folder, retrieved_at):
    folder = Path(folder)
    raw = (folder / 'items.json').read_bytes()
    items = json.loads(raw)
    build = json.loads((folder / 'stats-explained.json').read_text())['build']
    crafting, hashes = {}, {}
    for path in sorted((folder / 'crafting').glob('*.json')):
        payload = path.read_bytes()
        hashes[path.name] = hashlib.sha256(payload).hexdigest()
        crafting.update(json.loads(payload))
    records = []
    for item in sorted(items, key=lambda x: x['id']):
        recipes = [r for r in crafting.get(str(item['id']), {}).get('made', []) if r[0] in PROFESSIONS]
        if eligible(item) and recipes:
            records.append({'item': item, 'recipes': recipes})
    return {'_status': 'provisional', 'source': 'https://foreverdb.net/data/items.json',
            'recipeSource': 'https://foreverdb.net/data/crafting/{shard}.json',
            'sourceBuild': str(build), 'retrievedAt': retrieved_at,
            'sourceSha256': hashlib.sha256(raw).hexdigest(), 'recipeShardSha256': hashes, 'records': records}


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def render(data):
    if data.get('_status') != 'provisional':
        raise ValueError('External catalogs must remain provisional')
    records = data['records']
    ids = [r['item']['id'] for r in records]
    if len(ids) != len(set(ids)):
        raise ValueError('Duplicate item IDs')
    lines = ['-- Generated by tools/import_gear_catalog.py; do not edit.',
             '-- Client-derived item/recipe facts; access and usability are unconfirmed.',
             'local _, ns = ...', '', 'local items = {']
    classes = {name: [] for name in ARMOR_CLASS.values()}
    for index, record in enumerate(records, 1):
        item = record['item']
        if not eligible(item):
            raise ValueError(f'Unsupported starter item: {item["id"]}')
        stats = {'ARMOR': item['ar']}
        for stat, value in item['st']:
            if type(value) not in (int, float) or not math.isfinite(value) or value < 0:
                raise ValueError('Invalid item stat')
            key, divisor = STATS[stat]
            stats[key] = stats.get(key, 0) + value / divisor
        allowed = sorted(classes) if item['inv'] == 16 else [ARMOR_CLASS[item['sc']]]
        for cls in allowed:
            classes[cls].append(index)
        lines.extend(['  {', '    _status = "provisional",',
                      f'    itemID = {item["id"]}, name = {quote(item["n"])},',
                      f'    slot = {SLOTS[item["inv"]]}, minLevel = {max(item["rl"], item.get("el", 0))}, icon = {item["ic"]},',
                      '    classes = { ' + ', '.join(f'{c} = true' for c in allowed) + ' },',
                      '    stats = { ' + ', '.join(f'{k} = {v:g}' for k, v in sorted(stats.items())) + ' },',
                      '    routes = {'])
        if not record['recipes']:
            raise ValueError('Missing crafting route')
        seen = set()
        for recipe in record['recipes']:
            if len(recipe) != 5 or not isinstance(recipe[3], str) or not recipe[3]:
                raise ValueError('Malformed crafting recipe')
            prof, spell = recipe[:2]
            if prof not in PROFESSIONS or type(spell) is not int or spell <= 0 or spell in seen:
                raise ValueError('Invalid or duplicate recipe')
            seen.add(spell)
            lines.extend(['      {', '        _status = "provisional", kind = "craft",',
                          f'        key = "craft:{item["id"]}:{spell}", recipeID = {spell},',
                          f'        name = {quote(recipe[3])}, profession = {quote(PROFESSIONS[prof])},',
                          '      },'])
        lines.extend(['    },', '  },'])
    lines.extend(['}', '', 'ns.Data.GearCatalog = {', '  _status = "provisional",'])
    for key in ('source', 'recipeSource', 'sourceBuild', 'retrievedAt', 'sourceSha256'):
        lines.append(f'  {key} = {quote(data[key])},')
    for cls, indexes in sorted(classes.items()):
        lines.append(f'  {cls} = {{')
        for i in range(0, len(indexes), 8):
            lines.append('    ' + ', '.join(f'items[{j}]' for j in indexes[i:i + 8]) + ',')
        lines.append('  },')
    lines.extend(['}', ''])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--snapshot-dir', type=Path, help='create the dated input from raw ForeverDB JSON')
    parser.add_argument('--retrieved-at', help='original extraction date for a newly built snapshot')
    parser.add_argument('--check', action='store_true', help='check committed generated output')
    args = parser.parse_args()
    if args.snapshot_dir:
        if not args.retrieved_at:
            parser.error('--snapshot-dir requires the original --retrieved-at date')
        SOURCE.parent.mkdir(parents=True, exist_ok=True)
        SOURCE.write_text(json.dumps(snapshot(args.snapshot_dir, args.retrieved_at), ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    generated = render(json.loads(SOURCE.read_text(encoding='utf-8')))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != generated:
            parser.exit(1, 'GearCatalog.lua is stale; run tools/import_gear_catalog.py\n')
    else:
        OUTPUT.write_text(generated, encoding='utf-8')
    print('gear catalog: ok')


if __name__ == '__main__':
    main()
