#!/usr/bin/env python3
"""Generate ability learn levels and a Forever-vs-Classic change report.

Reads the preserved ForeverDB snapshot (data/external/full-snapshot.zip):

- classes.json -> Battleplan/Data/SpellRanks.lua: the level each rank of every
  trainer- or quest-taught ability is learned, for all nine classes.
- changes.json -> docs/FOREVER-CHANGES.md: what Forever changed from Classic per
  class (abilities, rank levels, talents, coefficients), names and numbers only.

Season of Discovery rune entries and "other" records (procs, effects, rank-0 passives)
are left out. Tooltip prose is never copied. Both outputs stay provisional until
a beta capture confirms them.

    python tools/import_class_data.py           # regenerate
    python tools/import_class_data.py --check   # fail if either output is stale
"""
import argparse
import hashlib
import json
import re
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARCHIVE = ROOT / 'data/external/full-snapshot.zip'
MANIFEST = ROOT / 'data/external/manifest.json'
RANKS_OUT = ROOT / 'Battleplan/Data/SpellRanks.lua'
CHANGES_OUT = ROOT / 'docs/FOREVER-CHANGES.md'
CLASSES_MEMBER = 'raw/foreverdb/classes.json'
CHANGES_MEMBER = 'raw/foreverdb/changes.json'
TAUGHT = ('trainer', 'quest')
RANK = re.compile(r'^Rank (\d+)$')


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def load(archive=None):
    """(classes, changes, provenance) from the archive, checked against the manifest."""
    manifest = json.loads(MANIFEST.read_text(encoding='utf-8'))
    hashes = {f['path']: f['sha256'] for f in manifest['files']}
    with zipfile.ZipFile(archive or ARCHIVE) as z:
        raw = {name: z.read(name) for name in (CLASSES_MEMBER, CHANGES_MEMBER)}
    for name, data in raw.items():
        if hashlib.sha256(data).hexdigest() != hashes.get(name):
            raise ValueError(f'{name} does not match data/external/manifest.json')
    provenance = {
        'sourceBuild': manifest['sourceBuild'],
        'retrievedAt': manifest['retrievedAt'][:10],
        'classesSha256': hashes[CLASSES_MEMBER],
        'changesSha256': hashes[CHANGES_MEMBER],
    }
    return json.loads(raw[CLASSES_MEMBER]), json.loads(raw[CHANGES_MEMBER]), provenance


def ability(cls, a):
    """One taught ability as a plain dict, or ValueError when its ranks don't parse."""
    ranks = a['ranks']
    entry = {'id': ranks[0]['id'], 'level': ranks[0]['lv']}
    # Unranked abilities carry the spellbook subtext instead ("Passive", "Summon",
    # "Shapeshift"); Reincarnation lists its passive and its spell at the same level.
    if not any(RANK.match(r['r']) for r in ranks):
        if len({r['lv'] for r in ranks}) != 1:
            raise ValueError(f'{cls}: unranked {a["n"]} has more than one learn level')
    else:
        numbers = [RANK.match(r['r']) for r in ranks]
        if not all(numbers) or [int(m.group(1)) for m in numbers] != list(range(1, len(ranks) + 1)):
            raise ValueError(f'{cls}: {a["n"]} ranks are not Rank 1..{len(ranks)}')
        levels = [r['lv'] for r in ranks]
        if levels != sorted(levels):
            raise ValueError(f'{cls}: {a["n"]} rank levels go down')
        entry['ranks'] = levels
    if not 1 <= entry['level'] <= 60:
        raise ValueError(f'{cls}: {a["n"]} learn level {entry["level"]} out of range')
    if a['src'] == 'quest':
        entry['quest'] = True
    if a.get('races'):
        entry['races'] = sorted(a['races'])
    if a.get('faction'):
        entry['faction'] = a['faction']
    return entry


def spell_ranks(classes):
    out = {}
    for c in classes:
        cls = c['n'].upper()
        table = {}
        for a in c['abilities']:
            if a.get('src') not in TAUGHT or a.get('rune') == 'sod':
                continue
            if a['n'] in table:
                raise ValueError(f'{cls}: duplicate ability {a["n"]}')
            table[a['n']] = ability(cls, a)
        out[cls] = table
    return out


def render_ranks(ranks, provenance):
    lines = [
        '-- Generated by tools/import_class_data.py; do not edit.',
        '-- Learn level of each rank of every trainer- or quest-taught ability, from the ForeverDB',
        '-- client snapshot. Season of Discovery runes and proc/effect records are left out.',
        '-- level: first rank; ranks[n]: level of Rank n; quest: taught by a quest, not a trainer.',
        'local _, ns = ...',
        '',
        'ns.Data.SpellRanks = {',
        '  _status = "provisional",',
        f'  source = {quote("https://foreverdb.net/data/classes.json")},',
        f'  sourceBuild = {quote(provenance["sourceBuild"])},',
        f'  retrievedAt = {quote(provenance["retrievedAt"])},',
        f'  sourceSha256 = {quote(provenance["classesSha256"])},',
    ]
    for cls in sorted(ranks):
        lines.append(f'  {cls} = {{')
        for name, e in sorted(ranks[cls].items()):
            parts = [f'id = {e["id"]}', f'level = {e["level"]}']
            if 'ranks' in e:
                parts.append('ranks = { ' + ', '.join(str(v) for v in e['ranks']) + ' }')
            if e.get('quest'):
                parts.append('quest = true')
            if 'races' in e:
                parts.append('races = { ' + ', '.join(quote(r) for r in e['races']) + ' }')
            if 'faction' in e:
                parts.append(f'faction = {quote(e["faction"])}')
            lines.append(f'    [{quote(name)}] = {{ ' + ', '.join(parts) + ' },')
        lines.append('  },')
    lines.extend(['}', ''])
    return '\n'.join(lines)


def section(lines, title, rows):
    if not rows:
        return
    lines.extend([f'**{title}**', ''])
    lines.extend(f'- {r}' for r in rows)
    lines.append('')


def spot(tree, tier, col):
    return f'{tree} tier {tier} column {col}'


def render_changes(classes, changes, provenance):
    names = {str(c['id']): c['n'] for c in classes}
    lines = [
        '<!-- Generated by tools/import_class_data.py; do not edit. -->',
        '# What Forever changed from Classic',
        '',
        f'Source: ForeverDB `changes.json`, client build {provenance["sourceBuild"]}, retrieved',
        f'{provenance["retrievedAt"]} (SHA-256 `{provenance["changesSha256"][:16]}...`). Provisional: the site',
        'compares the Forever client with Classic. Use it to find Classic assumptions in',
        "Battleplan's data; confirm anything the addon relies on with a probe capture.",
        'Names and numbers only; tooltip text changes are counted, not copied.',
        '',
    ]
    for cid in sorted(changes, key=int):
        v = changes[cid]
        lines.extend([f'## {names[cid]}', ''])
        level_rows = []
        for a in v['abilitiesChanged']:
            moved = [f'{r or "learned"} {old} to {new}' for r, old, new in a['levels'] if old != new]
            detail = '; '.join(moved)
            if a['ranksAdded']:
                detail += ('; ' if detail else '') + 'adds ' + ', '.join(a['ranksAdded'])
            if a['ranksRemoved']:
                detail += ('; ' if detail else '') + 'drops ' + ', '.join(a['ranksRemoved'])
            name = a['n'] if a['fn'] == a['n'] else f'{a["n"]} (now {a["fn"]})'
            level_rows.append(f'{name}: {detail or "changed"}')
        section(lines, 'Ability levels and ranks (Classic to Forever)', level_rows)
        section(lines, 'Abilities removed', [a['n'] for a in v['abilitiesRemoved']])
        section(lines, 'In the client but not taught', [a['n'] for a in v['abilitiesInClientNotTaught']])
        section(lines, 'No longer trained', [f'{a["n"]} (now {a["now"]})' for a in v['abilitiesNotTrained']])
        section(lines, 'Abilities merged', [f'{a["fn"]} (from {", ".join(a["from"])})' for a in v['abilitiesMerged']])
        section(lines, 'Talents removed', [f'{t["n"]} ({t["tree"]})' for t in v['talentsRemoved']])
        section(lines, 'Talents replaced', [f'{t["n"]} ({t["tree"]}) by {t["fn"]} ({t["ftree"]})'
                                            for t in v['talentsReplaced']])
        section(lines, 'Talents added', [f'{t["n"]} ({t["ftree"]}, tier {t["ftier"]}, {t["franks"]} rank'
                                         f'{"s" if t["franks"] != 1 else ""})' for t in v['talentsAdded']])
        section(lines, 'Talents now baseline', [f'{t["n"]} (trained at {t["flv"]})' for t in v['talentsBaseline']])
        section(lines, 'Talents hidden', [f'{t["n"]} ({t["tree"]})' for t in v['talentsHidden']])
        section(lines, 'Talent ranks changed', [f'{t["n"]}: {t["ranks"]} to {t["franks"]}'
                                                for t in v['talentRanksChanged']])
        section(lines, 'Talents moved', [f'{t["n"]}: {spot(t["tree"], t["tier"], t["col"])} to '
                                         f'{spot(t["ftree"], t["ftier"], t["fcol"])}' for t in v['talentsMoved']])
        section(lines, 'Spell coefficients', [f'{c["n"]} {c["r"]}: {c["old"]:g} to {c["new"]:g}'.replace('  ', ' ')
                                              for c in v['coefficientChanges']])
        section(lines, 'Weapon skills', [f'{p["skill"]}: {p["change"]} at level {p["lv"]}' for p in v['proficiency']])
        if v['tooltipChanges']:
            lines.extend([f'{len(v["tooltipChanges"])} tooltips reworded.', ''])
    return '\n'.join(lines).rstrip('\n') + '\n'


def build(archive=None):
    classes, changes, provenance = load(archive)
    return (render_ranks(spell_ranks(classes), provenance),
            render_changes(classes, changes, provenance))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='fail if a generated file is stale')
    args = parser.parse_args()
    outputs = dict(zip((RANKS_OUT, CHANGES_OUT), build()))
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                parser.exit(1, f'{path.relative_to(ROOT)} is stale; run tools/import_class_data.py\n')
        else:
            path.write_text(text, encoding='utf-8', newline='\n')
    print('class data: ok')


if __name__ == '__main__':
    main()
